name: fruit_hub_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  firebase_core: ^3.4.0
  firebase_storage: ^12.3.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
